[platformio]
src_dir = core

[env:esp32s3-zero]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino

; Waveshare ESP32-S3-Zero-N8R8 / ESP32-S3-PICO-1:
; 8 MB quad flash, 8 MB octal PSRAM.
board_build.flash_size = 8MB
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 8MB

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -D_IR_ENABLE_DEFAULT_=false
    -DSEND_PANASONIC_AC=true
    -DDECODE_PANASONIC_AC=true
    -DSEND_DAIKIN=true
    -DDECODE_DAIKIN=true
    -DSEND_DAIKIN2=true
    -DDECODE_DAIKIN2=true
    -DSEND_DAIKIN64=true
    -DDECODE_DAIKIN64=true
    -DSEND_DAIKIN128=true
    -DDECODE_DAIKIN128=true
    -DSEND_DAIKIN152=true
    -DDECODE_DAIKIN152=true
    -DSEND_DAIKIN160=true
    -DDECODE_DAIKIN160=true
    -DSEND_DAIKIN176=true
    -DDECODE_DAIKIN176=true
    -DSEND_DAIKIN200=true
    -DDECODE_DAIKIN200=true
    -DSEND_DAIKIN216=true
    -DDECODE_DAIKIN216=true
    -DSEND_DAIKIN312=true
    -DDECODE_DAIKIN312=true
    -DSEND_MITSUBISHI_AC=true
    -DDECODE_MITSUBISHI_AC=true
    -DSEND_MITSUBISHI136=true
    -DDECODE_MITSUBISHI136=true
    -DSEND_MITSUBISHI112=true
    -DDECODE_MITSUBISHI112=true
    -DSEND_MITSUBISHIHEAVY=true
    -DDECODE_MITSUBISHIHEAVY=true
    -DSEND_HITACHI_AC=true
    -DDECODE_HITACHI_AC=true
    -DSEND_HITACHI_AC1=true
    -DDECODE_HITACHI_AC1=true
    -DSEND_HITACHI_AC2=true
    -DDECODE_HITACHI_AC2=true
    -DSEND_HITACHI_AC3=true
    -DDECODE_HITACHI_AC3=true
    -DSEND_HITACHI_AC264=true
    -DDECODE_HITACHI_AC264=true
    -DSEND_HITACHI_AC296=true
    -DDECODE_HITACHI_AC296=true
    -DSEND_HITACHI_AC344=true
    -DDECODE_HITACHI_AC344=true
    -DSEND_HITACHI_AC424=true
    -DDECODE_HITACHI_AC424=true
    -DSEND_GREE=true
    -DDECODE_GREE=true
    -DSEND_MIDEA=true
    -DDECODE_MIDEA=true
    -DSEND_SAMSUNG_AC=true
    -DDECODE_SAMSUNG_AC=true
    -DSEND_LG=true
    -DDECODE_LG=true
    -DSEND_TOSHIBA_AC=true
    -DDECODE_TOSHIBA_AC=true

lib_deps =
    links2004/WebSockets@^2.4.1
    crankyoldgit/IRremoteESP8266@^2.8.6
    bblanchon/ArduinoJson@^7.0.0

monitor_speed = 115200
